# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b478a88d486f471b68f803a4e7a744a5e0167cb854b617413bc47e05e9a101a7e5f0a502310e5971ef9c901135701be16db2f6aff027bd14f58d18c0b1eff1

test:
  secret_key_base: 8a7acf6c1447cc928fb3f650fef28f80fe0e8599572d3ae5e46554f5758cb96cbe3a78be0f8e3dea7aa308bb8f7985a80c81e6c9ac7414870cbac248b1eb7ba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
